
modLoader="javafml" #//mandatory
loaderVersion="[36,42)" # // mandatory. This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"
issueTrackerURL="${issues}"


[[mods]] #//mandatory
	modId="lod" #//mandatory
	version= "${version}" #//mandatory, gets the version number from jar populated by the build.gradle script
	displayName="${mod_name}" #//mandatory
	authors=$authors
	#//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
	displayURL="${homepage}"
	description= "${description}" #//mandatory. The description text for the mod
	logoFile="logo.png"
	catalogueImageIcon="icon.png"
	credits="Leonardo, Cola, Ran, CoolGi, and Leetom. Without their hard work, Distant Horizons wouldn't be the mod it is today."
	#// if not set defaults to "false"
	clientSideOnly="true"
	#// if not set defaults to "BOTH"
	#// TODO change to "BOTH" when we add server support
	side="CLIENT"
	#// Allow any version to be present (or not) on the server
	acceptableRemoteVersions="*"

[[dependencies.lod]]
	modId="forge"
	mandatory=true
	versionRange="[41.0.95,)" #// NOTE: this will cause issues for anything using MC 1.18 and lower, this is only here for MC 1.19
	ordering="NONE"
	side="BOTH"