plugins {
    id 'dh-loader'
}

unimined.minecraft {
    cleanroom {
        loader gradle.ext.cleanroom_loader_version
        useToolchains = false
        accessTransformer project(":common").file("src/main/resources/${gradle.ext.accessWidenerVersion}.distanthorizons_at.cfg")
    }
    mods {
        remap(configurations.modCompileOnly)
        remap(configurations.modRuntimeOnly)
    }
}